### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by mozey** [apex/gateway#17]
With gateway a single Lambda function might handle many API Gateway requests, what happens when it exceeds the allocated memory? 

It seems like AWS Lambda is somewhat flexible with the amount of memory the function may use, and I assume it will then start another if the account has concurrency available?

**Comment by mozey** [comment]
> You're only ever handling one request in a single Lambda container

Ah I thought variables outside the callback passed into `lambda.Start` might persist across requests depending on how long AWS chooses to keep the container alive. 

But if each API Gateway request gets at least 128MB and it's own container, then that's not an issue.

**Comment by tj** [comment]
What you said is correct actually, you could bloat the memory with a bad caching algorithm or something but in practice I've never exceeded even the 128mb limit
