### ISSUE TITLE
Is it possible to include assets in the binary?

### ISSUE THREAD

**Issue by dre2004** [apex/gateway#24]
Hello, 

I've only just come across this library and I think it's great! I was trying to figure out how I could build some small generic tools that run directly on lambda for mostly house keeping tasks and I think this will do the trick.

I was wondering though, is it possible to use something like packr to include (a very small amount) of files within my go binary?

I've literally just done a drop in replacement for the gin app I was working on and it's deployed fine to lambda and serves my gin site but I was hoping to be able to include a couple of css, js files with this rather than hosting those in s3 or elsewhere.

**Comment by tj** [comment]
Yep you can use tools like go-bindata or the one you mentioned :D or since it's a zip file in Lambda you can just store them in your zip as well
