### ISSUE TITLE
Set request.RequestURI

### ISSUE THREAD

**Issue by carlmjohnson** [apex/gateway#26]
`Request.URL` is set, but not `Request.RequestURI`. This causes problems with certain logging middleware.

**Comment by piotrkubisa** [comment]
I remember, I got similar issue as you reported in #26 while I was trying to re-use `github.com/go-chi/chi/middleware.Logger`. In my re-implementation of apex/gateway, I have made a following commit https://github.com/piotrkubisa/apigo/commit/6de39ca9cf9767b06500b5cf7807524747f1ad85. Knowing a fact the API Gateway/Netflify uses HTTPS, it is worth setting `*http.Request.TLS = &tls.ConnectionState{}` too.

**Comment by jainpiyush19** [comment]
This is failing with `https://github.com/dimfield/httptreemux` v5 since request.RequestURI must be complete path with query params. Current implementation `e.Path` only gives the path without query params

**Comment by carlmjohnson** [comment]
@jainpiyush19 I updated my fork to use the query parameters.

**Comment by jainpiyush19** [comment]
@carlmjohnson Thanks. Will you be raising a PR on the main repo?

**Comment by carlmjohnson** [comment]
No, my fork has diverged and I’m not interested in figuring out how to reconcile with apex’s version. But you can probably just cherry-pick it and open a PR if you prefer their version.
