### ISSUE TITLE
Not compatible with gateway v2

### ISSUE THREAD

**Issue by tcurdt** [apex/gateway#31]
This code works just fine.

```
package main

import (
 "context"
 "fmt"

 "github.com/aws/aws-lambda-go/lambda"
)

func HandleRequest(ctx context.Context) (string, error) {
  return fmt.Sprintf("Hello!"), nil
}

func main() {
  lambda.Start(HandleRequest)
}
```

When I replace it with

```
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/apex/gateway"
)

func main() {

	http.HandleFunc("/", hello)

	log.Fatal(gateway.ListenAndServe(":3000", nil))
	// log.Fatal(http.ListenAndServe(":3000", nil))
}

func hello(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello!")
}
```

I am getting:

```
curl https://dqt4t5gx.execute-api.eu-central-1.amazonaws.com/
<a href="//dqt4t5gx.execute-api.eu-central-1.amazonaws.com/">Moved Permanently</a>.
```

Could this be because I am using the `aws_apigatewayv2_api` resource?
Or any other pointers?

**Comment by tcurdt** [comment]
After some debugging

```
import (
	"context"
	"log"
	"net/http"

	"github.com/apex/gateway"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/go-chi/chi"
)

func ListenAndServe(addr string, h http.Handler) error {
	if h == nil {
		h = http.DefaultServeMux
	}

	lambda.Start(func(ctx context.Context, e events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {

		r, err := gateway.NewRequest(ctx, e)
		if err != nil {
			// return events.APIGatewayProxyResponse{Body: "error", StatusCode: 200}, nil
			return events.APIGatewayProxyResponse{}, err
		}
		// return events.APIGatewayProxyResponse{Body: "ok1", StatusCode: 200}, nil

		w := gateway.NewResponse()
		h.ServeHTTP(w, r)

		// return events.APIGatewayProxyResponse{Body: "ok2", StatusCode: 200}, nil

		return w.End(), nil
	})

	return nil
}

func main() {
	// http.ListenAndServe(":3000", routing())
	// gateway.ListenAndServe(":3000", routing())
	ListenAndServe(":3000", routing())
}

func routing() http.Handler {

	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("Hello World"))
	})

	r.Get("/id/{id}", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("id: %s", chi.URLParam(r, "id"))
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("Hello World"))
	})

	return r
}
```

I see that `h.ServeHTTP` seems to generate the 404 when using `gateway`. This also is the case when using `chi`. When running directly it works just fine.

**Comment by tcurdt** [comment]
It seems the `RequestURI` is empty although it should be `/`. So the router does not match and falls back to a 404.

**Comment by tcurdt** [comment]
```
func NewRequest(ctx context.Context, e events.APIGatewayProxyRequest) (*http.Request, error) {
	// path
	u, err := url.Parse(e.Path)
```

parses the path but the URL has no `/` suffix. When the URL gets passed into the new request, the URL path is "" not "/" which makes the router not find it.

```
	// new request
	req, err := http.NewRequest(e.HTTPMethod, u.String(), strings.NewReader(body))
	if err != nil {
		return nil, errors.Wrap(err, "creating request")
	}
```

Now the question is how to fix this best - and why this wasn't an issue before.

**Comment by tcurdt** [comment]
Digging further it seems like `e.Path` is not giving the path at all. 
I have a lambda mounted as "ANY /{proxy+}". This should catch all paths.

Doing a

```
curl https://uc3h7ht2.execute-api.eu-central-1.amazonaws.com/foo/bla
```
I would expect the `e.Path` to be `/foo/bla` (or `foo/bla`) but `e.Path` is just empty.

**Comment by tcurdt** [comment]
Seems like it could be related to this https://github.com/aws/aws-lambda-go/issues/60

**Comment by tcurdt** [comment]
This seems to be an issue with aws-lambda-go - not gateway itself.
I've opened https://github.com/aws/aws-lambda-go/issues/297

I will close this issue as soon as I hear back from them.

**Comment by tcurdt** [comment]
Alright - the problem is that the current `gateway` is not v2 compatible.

I've upgrade my version here for now. The question is - how should this be handled. There is no easy migration path as the AWS resources are different. 

Any other suggestions?

**Comment by tj** [comment]
Relevant PR to follow: #30

**Comment by Grabber** [comment]
> I've upgrade my version here for now. The question is - how should this be handled. There is no easy migration path as the AWS resources are different.

What have you changed to make it work until v2 is not fully compatible?

**Comment by tcurdt** [comment]
The recent v2 addition is working fine for me now. Hence I am closing the issue.

```
package main

import (
  "fmt"
  "net/http"

  "github.com/apex/gateway/v2"
  "github.com/go-chi/chi"
)

func main() {
  gateway.ListenAndServe(":3000", routing())
}

func routing() http.Handler {

  r := chi.NewRouter()

  r.Get("/", func(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)
    w.Write([]byte("Hello World"))
  })

  r.Get("/id/{id}", func(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)
    w.Write([]byte("Hello World"))
  })

  r.NotFound(func(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)
    w.Write([]byte(fmt.Sprintf("Not found: [%s]", r.RequestURI)))
  })

  return r
}
```

@Grabber I suggest to check your gateway setup first. Is it really a v2 or is it a v1 gateway? Next add a "not found" handler and output the path. See if the path is what you would expect. If not, you will need to dig a bit into `gin` and how it does the route matching.
